clear all;
clc;
% Codebook Type enumerations:
% codebookType
% 0 - Type I - Single Panel
% 1 - Type I - Multi Panel
% 2 - Type II
% 3 - Type II - Port Selection

% Ng - Number of panel
% N1 - Number of horizontal antenna element (azimuth)
% N2 - Number of vertical antenna element (elevation)
% O1 - Oversampling of horizontal antenna element (azimuth)
% O2 - Oversampling of vertical antenna element (elevation)
% L - Number of layer

% i11 - Steer beams in horizontal
% i12 - Steer beams in vertical

% Configurations

c = 3e8;        % propagation speed
fc = 3.5e9;     % carrier frequency
lambda = c/fc;	% wavelength

Ng = 4; % Number of sub-array
N1 = 4; % Number of horizontal antenna elements
N2 = 2; % Number of vertical antenna elements
O1 = 4; % Number of horizontal oversampling factor
O2 = 4; % Number of vertical oversampling factor
   
L = 1;

codebookMode = 1;
codebookType = 1;   % Type I - Multi Panel Panel

i11 = 1;
i12 = 1;
i13 = 0;
i2 = 0;
i3 = 0;
i141 = 1;
i142 = 1;
i143 = 1;
plot = 1;

%w = codebook(codebookType, L, codebookMode, i11, i12, i13, i2, N1, N2, O1, O2);

%% Set up beam
antennaElement = phased.CrossedDipoleAntennaElement; % dinh nghia phan cuc tron
% generate crossed-dipole antenna
% generate circularly polarized field: left and right
%antennaElement = phased.IsotropicAntennaElement;
if N2 ~= 1
    txarray = phased.URA('Size',[N1*O1 N2*O2],'ElementSpacing',[lambda/2 lambda/2],...
        'Element',antennaElement);
    % Uniform Rectangular Array
     
elseif N2 == 1
    txarray = phased.ULA('NumElements',N1*N2*O1*O2,'ElementSpacing',lambda/2,...
        'Element',antennaElement); 
    % Uniform Linear Array
end
pos = getElementPosition(txarray);
% for i11 = 1:1:15

%               w = codebook(codebookType, L, codebookMode, i11, i12, i13, i2,...
%                     N1, N2, O1, O2);
        w = Four_Panel_4_Layer_Mode_1(i11,i12,i13,i141,i142,i143,i2,Ng,N1,N2,O1,O2);
                w_1layer = w(:,1);
                w_2layer = w(:,2);
                w_3layer = w(:,3);
                w_4layer = w(:,4);
                
%% matrix with layer 1 in 4 layer.
                w1_1layer = w_1layer(1:numel(w_1layer)/8); 
                w2_1layer = w_1layer(numel(w_1layer)/8+1:numel(w_1layer)*(2/8)); 
                w3_1layer = w_1layer(numel(w_1layer)*(2/8)+1:numel(w_1layer)*(3/8));
                w4_1layer = w_1layer(numel(w_1layer)*(3/8)+1:numel(w_1layer)*(4/8));
                w5_1layer = w_1layer(numel(w_1layer)*(4/8)+1:numel(w_1layer)*(5/8));
                w6_1layer = w_1layer(numel(w_1layer)*(5/8)+1:numel(w_1layer)*(6/8));
                w7_1layer = w_1layer(numel(w_1layer)*(6/8)+1:numel(w_1layer)*(7/8));
                w8_1layer = w_1layer(numel(w_1layer)*(7/8)+1:end);
                

                w1_s_1layer = reshape(w1_1layer, N2,N1).'; 
                w1_s_1layer = kron(w1_s_1layer,ones(O1,O2)); 
                wt1_1layer = reshape(w1_s_1layer.',[],1); 

                w2_s_1layer = reshape(w2_1layer, N2,N1).'; 
                w2_s_1layer = kron(w2_s_1layer,ones(O1,O2));
                wt2_1layer = reshape(w2_s_1layer.',[],1);

                w3_s_1layer = reshape(w3_1layer, N2,N1).'; 
                w3_s_1layer = kron(w3_s_1layer,ones(O1,O2));
                wt3_1layer = reshape(w3_s_1layer.',[],1);
                
                w4_s_1layer = reshape(w4_1layer, N2,N1).'; 
                w4_s_1layer = kron(w4_s_1layer,ones(O1,O2));
                wt4_1layer = reshape(w4_s_1layer.',[],1);
                
                w5_s_1layer = reshape(w5_1layer, N2,N1).'; 
                w5_s_1layer = kron(w5_s_1layer,ones(O1,O2));
                wt5_1layer = reshape(w5_s_1layer.',[],1);
                
                w6_s_1layer = reshape(w6_1layer, N2,N1).'; 
                w6_s_1layer = kron(w6_s_1layer,ones(O1,O2));
                wt6_1layer = reshape(w6_s_1layer.',[],1);
                
                w7_s_1layer = reshape(w7_1layer, N2,N1).'; 
                w7_s_1layer = kron(w7_s_1layer,ones(O1,O2));
                wt7_1layer = reshape(w7_s_1layer.',[],1);
                
                w8_s_1layer = reshape(w8_1layer, N2,N1).'; 
                w8_s_1layer = kron(w8_s_1layer,ones(O1,O2));
                wt8_1layer = reshape(w8_s_1layer.',[],1);
                
%% matrix with layer 2 in 4 layer.
                w1_2layer = w_2layer(1:numel(w_2layer)/8); 
                w2_2layer = w_2layer(numel(w_2layer)/8+1:numel(w_2layer)*(2/8)); 
                w3_2layer = w_2layer(numel(w_2layer)*(2/8)+1:numel(w_2layer)*(3/8));
                w4_2layer = w_2layer(numel(w_2layer)*(3/8)+1:numel(w_2layer)*(4/8));
                w5_2layer = w_2layer(numel(w_2layer)*(4/8)+1:numel(w_2layer)*(5/8));
                w6_2layer = w_2layer(numel(w_2layer)*(5/8)+1:numel(w_2layer)*(6/8));
                w7_2layer = w_2layer(numel(w_2layer)*(6/8)+1:numel(w_2layer)*(7/8));
                w8_2layer = w_2layer(numel(w_2layer)*(7/8)+1:end);

                w1_s_2layer = reshape(w1_2layer, N2,N1).'; 
                w1_s_2layer = kron(w1_s_2layer,ones(O1,O2)); 
                wt1_2layer = reshape(w1_s_2layer.',[],1); 

                w2_s_2layer = reshape(w2_2layer, N2,N1).'; 
                w2_s_2layer = kron(w2_s_2layer,ones(O1,O2));
                wt2_2layer = reshape(w2_s_2layer.',[],1);

                w3_s_2layer = reshape(w3_2layer, N2,N1).'; 
                w3_s_2layer = kron(w3_s_2layer,ones(O1,O2));
                wt3_2layer = reshape(w3_s_2layer.',[],1);
                
                w4_s_2layer = reshape(w4_2layer, N2,N1).'; 
                w4_s_2layer = kron(w4_s_2layer,ones(O1,O2));
                wt4_2layer = reshape(w4_s_2layer.',[],1);
                
                w5_s_2layer = reshape(w5_2layer, N2,N1).'; 
                w5_s_2layer = kron(w5_s_2layer,ones(O1,O2));
                wt5_2layer = reshape(w5_s_2layer.',[],1);
                
                w6_s_2layer = reshape(w6_2layer, N2,N1).'; 
                w6_s_2layer = kron(w6_s_2layer,ones(O1,O2));
                wt6_2layer = reshape(w6_s_2layer.',[],1);
                
                w7_s_2layer = reshape(w7_2layer, N2,N1).'; 
                w7_s_2layer = kron(w7_s_2layer,ones(O1,O2));
                wt7_2layer = reshape(w7_s_2layer.',[],1);
                
                w8_s_2layer = reshape(w8_2layer, N2,N1).'; 
                w8_s_2layer = kron(w8_s_2layer,ones(O1,O2));
                wt8_2layer = reshape(w8_s_2layer.',[],1);
%% matrix with layer 3 in 3 layer.
                w1_3layer = w_3layer(1:numel(w_3layer)/8); 
                w2_3layer = w_3layer(numel(w_3layer)/8+1:numel(w_3layer)*(2/8)); 
                w3_3layer = w_3layer(numel(w_3layer)*(2/8)+1:numel(w_3layer)*(3/8));
                w4_3layer = w_3layer(numel(w_3layer)*(3/8)+1:numel(w_3layer)*(4/8));
                w5_3layer = w_3layer(numel(w_3layer)*(4/8)+1:numel(w_3layer)*(5/8));
                w6_3layer = w_3layer(numel(w_3layer)*(5/8)+1:numel(w_3layer)*(6/8));
                w7_3layer = w_3layer(numel(w_3layer)*(6/8)+1:numel(w_3layer)*(7/8));
                w8_3layer = w_3layer(numel(w_3layer)*(7/8)+1:end);

                w1_s_3layer = reshape(w1_3layer, N2,N1).'; 
                w1_s_3layer = kron(w1_s_3layer,ones(O1,O2)); 
                wt1_3layer = reshape(w1_s_3layer.',[],1); 

                w2_s_3layer = reshape(w2_3layer, N2,N1).'; 
                w2_s_3layer = kron(w2_s_3layer,ones(O1,O2));
                wt2_3layer = reshape(w2_s_3layer.',[],1);

                w3_s_3layer = reshape(w3_3layer, N2,N1).'; 
                w3_s_3layer = kron(w3_s_3layer,ones(O1,O2));
                wt3_3layer = reshape(w3_s_3layer.',[],1);
                
                w4_s_3layer = reshape(w4_3layer, N2,N1).'; 
                w4_s_3layer = kron(w4_s_3layer,ones(O1,O2));
                wt4_3layer = reshape(w4_s_3layer.',[],1);
                
                w5_s_3layer = reshape(w5_3layer, N2,N1).'; 
                w5_s_3layer = kron(w5_s_3layer,ones(O1,O2));
                wt5_3layer = reshape(w5_s_3layer.',[],1);
                
                w6_s_3layer = reshape(w6_3layer, N2,N1).'; 
                w6_s_3layer = kron(w6_s_3layer,ones(O1,O2));
                wt6_3layer = reshape(w6_s_3layer.',[],1);
                
                w7_s_3layer = reshape(w7_3layer, N2,N1).'; 
                w7_s_3layer = kron(w7_s_3layer,ones(O1,O2));
                wt7_3layer = reshape(w7_s_3layer.',[],1);
                
                w8_s_3layer = reshape(w8_3layer, N2,N1).'; 
                w8_s_3layer = kron(w8_s_3layer,ones(O1,O2));
                wt8_3layer = reshape(w8_s_3layer.',[],1);
                
%% matrix with layer 4 in 4 layer.
                w1_4layer = w_4layer(1:numel(w_4layer)/8); 
                w2_4layer = w_4layer(numel(w_4layer)/8+1:numel(w_4layer)*(2/8)); 
                w3_4layer = w_4layer(numel(w_4layer)*(2/8)+1:numel(w_4layer)*(3/8));
                w4_4layer = w_4layer(numel(w_4layer)*(3/8)+1:numel(w_4layer)*(4/8));
                w5_4layer = w_4layer(numel(w_4layer)*(4/8)+1:numel(w_4layer)*(5/8));
                w6_4layer = w_4layer(numel(w_4layer)*(5/8)+1:numel(w_4layer)*(6/8));
                w7_4layer = w_4layer(numel(w_4layer)*(6/8)+1:numel(w_4layer)*(7/8));
                w8_4layer = w_4layer(numel(w_4layer)*(7/8)+1:end);

                w1_s_4layer = reshape(w1_4layer, N2,N1).'; 
                w1_s_4layer = kron(w1_s_4layer,ones(O1,O2)); 
                wt1_4layer = reshape(w1_s_4layer.',[],1); 

                w2_s_4layer = reshape(w2_4layer, N2,N1).'; 
                w2_s_4layer = kron(w2_s_4layer,ones(O1,O2));
                wt2_4layer = reshape(w2_s_4layer.',[],1);

                w3_s_4layer = reshape(w3_4layer, N2,N1).'; 
                w3_s_4layer = kron(w3_s_4layer,ones(O1,O2));
                wt3_4layer = reshape(w3_s_4layer.',[],1);
                
                w4_s_4layer = reshape(w4_4layer, N2,N1).'; 
                w4_s_4layer = kron(w4_s_4layer,ones(O1,O2));
                wt4_4layer = reshape(w4_s_4layer.',[],1);
                
                w5_s_4layer = reshape(w5_4layer, N2,N1).'; 
                w5_s_4layer = kron(w5_s_4layer,ones(O1,O2));
                wt5_4layer = reshape(w5_s_4layer.',[],1);
                
                w6_s_4layer = reshape(w6_4layer, N2,N1).'; 
                w6_s_4layer = kron(w6_s_4layer,ones(O1,O2));
                wt6_4layer = reshape(w6_s_4layer.',[],1);
                
                w7_s_4layer = reshape(w7_4layer, N2,N1).'; 
                w7_s_4layer = kron(w7_s_4layer,ones(O1,O2));
                wt7_4layer = reshape(w7_s_4layer.',[],1);
                
                w8_s_4layer = reshape(w8_4layer, N2,N1).'; 
                w8_s_4layer = kron(w8_s_4layer,ones(O1,O2));
                wt8_4layer = reshape(w8_s_4layer.',[],1);
%% figure 3D
                hFig = figure(1);
                set(gcf,'color','w');

                subplot(4,2,1); 
                pattern(txarray,fc,[-180:180],[-90:90],...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',(wt1_1layer + wt1_2layer + wt1_3layer + wt1_4layer));
                tStr = sprintf('i_{11} = %d, i_{12} = %d, i_2 = %d',i11,i12,i2);
                title(tStr);

                subplot(4,2,2); % o thu 2
                pattern(txarray,fc,[-180:180],[-90:90],...  
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',(wt2_1layer + wt2_2layer + wt2_3layer + wt2_4layer));
                tStr = sprintf('i_{11} = %d, i_{12} = %d, i_2 = %d',i11,i12,i2);
                title(tStr);
                
                subplot(4,2,3); % o thu 2
                pattern(txarray,fc,[-180:180],[-90:90],...  
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',(wt3_1layer + wt3_2layer + wt3_3layer + wt3_4layer));
                tStr = sprintf('i_{11} = %d, i_{12} = %d, i_2 = %d',i11,i12,i2);
                title(tStr);
                
                subplot(4,2,4); % o thu 2
                pattern(txarray,fc,[-180:180],[-90:90],...  
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',(wt4_1layer + wt4_2layer + wt4_3layer + wt4_4layer));
                tStr = sprintf('i_{11} = %d, i_{12} = %d, i_2 = %d',i11,i12,i2);
                title(tStr);
                
                subplot(4,2,5); % o thu 2
                pattern(txarray,fc,[-180:180],[-90:90],...  
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',(wt5_1layer + wt5_2layer + wt5_3layer + wt5_4layer));
                tStr = sprintf('i_{11} = %d, i_{12} = %d, i_2 = %d',i11,i12,i2);
                title(tStr);
                
                subplot(4,2,6); % o thu 2
                pattern(txarray,fc,[-180:180],[-90:90],...  
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',(wt6_1layer + wt6_2layer + wt6_3layer + wt6_4layer));
                tStr = sprintf('i_{11} = %d, i_{12} = %d, i_2 = %d',i11,i12,i2);
                title(tStr);
                
                subplot(4,2,7); % o thu 2
                pattern(txarray,fc,[-180:180],[-90:90],...  
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',(wt7_1layer + wt7_2layer + wt7_3layer + wt7_4layer));
                tStr = sprintf('i_{11} = %d, i_{12} = %d, i_2 = %d',i11,i12,i2);
                title(tStr);
                
                subplot(4,2,8); % o thu 2
                pattern(txarray,fc,[-180:180],[-90:90],...  
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',(wt8_1layer + wt8_2layer + wt8_3layer + wt8_4layer));
                tStr = sprintf('i_{11} = %d, i_{12} = %d, i_2 = %d',i11,i12,i2);
                title(tStr);
                    
                %% figure 2D
                hFig = figure(2);
                AzRange = -180:1:180;
                ElRange = -90:1:90; 
                % Plot Array Factor - Azimuth
                subplot(2,2,1);
                az11 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt1_1layer);
                
                az12 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt1_2layer);
                az13 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt1_3layer);
                az14 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt1_4layer);
                
                az21 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt2_1layer);
                
                az22 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt2_2layer);
                az23 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt2_3layer);
                az24 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt2_4layer);
                
                az31 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt3_1layer);
                
                az32 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt3_2layer);
                az33 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt3_3layer);
                az34 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt3_4layer);
                
                az41 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt4_1layer);
                
                az42 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt4_2layer);
                az43 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt4_3layer);
                az44 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt4_4layer);
                
                az51 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt5_1layer);
                
                az52 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt5_2layer);
                az53 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt5_3layer);
                az54 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt5_4layer);
                
                az61 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt6_1layer);
                
                az62 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt6_2layer);
                az63 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt6_3layer);
                az64 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt6_4layer);
                
                az71 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt7_1layer);
                
                az72 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt7_2layer);
                az73 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt7_3layer);
                az74 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt7_4layer);
                
                az81 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt8_1layer);
                
                az82 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt8_2layer);
                az83 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt8_3layer);
                az84 = pattern(txarray,fc,AzRange,0,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt8_4layer);
                
                subplot(4,4,1);
                clear plot
                plot(AzRange,az11,"b",AzRange,az12,"r",AzRange,az13,"g",AzRange,az14,"y");
                axis ([-100 100 -50 0]);
                grid on;
                
                subplot(4,4,3);
                clear plot
                plot(AzRange,az21,"b",AzRange,az22,"r",AzRange,az23,"g",AzRange,az24,"y");
                axis ([-100 100 -50 0]);
                grid on;
                
                subplot(4,4,5);
                clear plot
                plot(AzRange,az31,"b",AzRange,az32,"r",AzRange,az33,"g",AzRange,az34,"y");
                axis ([-100 100 -50 0]);
                grid on;
                
                subplot(4,4,7);
                clear plot
                plot(AzRange,az41,"b",AzRange,az42,"r",AzRange,az43,"g",AzRange,az44,"y");
                axis ([-100 100 -50 0]);
                grid on;
                
                subplot(4,4,9);
                clear plot
                plot(AzRange,az51,"b",AzRange,az52,"r",AzRange,az53,"g",AzRange,az54,"y");
                axis ([-100 100 -50 0]);
                grid on;
                
                subplot(4,4,11);
                clear plot
                plot(AzRange,az61,"b",AzRange,az62,"r",AzRange,az63,"g",AzRange,az64,"y");
                axis ([-100 100 -50 0]);
                grid on;
                
                subplot(4,4,13);
                clear plot
                plot(AzRange,az71,"b",AzRange,az72,"r",AzRange,az73,"g",AzRange,az74,"y");
                axis ([-100 100 -50 0]);
                grid on;
                
                subplot(4,4,15);
                clear plot
                plot(AzRange,az81,"b",AzRange,az82,"r",AzRange,az83,"g",AzRange,az84,"y");
                axis ([-100 100 -50 0]);
                grid on;
                
                % Plot Array Factor - Elevation
%                 pattern(txarray,fc,0,ElRange,...
%                     'PropagationSpeed',c,...
%                     'CoordinateSystem','polar',...
%                     'Type','powerdB',...
%                     'Weights',wt1_1layer);
                
                el11 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt1_1layer);
                
                el12 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt1_2layer);
                el13 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt1_3layer);
                el14 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt1_4layer);
                
                
                el21 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt2_1layer);
                
                el22 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt2_2layer);
                el23 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt2_3layer);
                el24 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt2_4layer);
                
                el31 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt3_1layer);
                
                el32 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt3_2layer);
                el33 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt3_3layer);
                el34 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt3_4layer);
                
                el41 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt4_1layer);
                
                el42 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt4_2layer);
                el43 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt4_3layer);
                el44 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt4_4layer);
                
                el51 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt5_1layer);
                
                el52 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt5_2layer);
                el53 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt5_3layer);
                el54 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt5_4layer);
                
                el61 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt6_1layer);
                
                el62 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt6_2layer);
                el63 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt6_3layer);
                el64 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt6_4layer);
                
                el71 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt7_1layer);
                
                el72 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt7_2layer);
                el73 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt7_3layer);
                el74 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt7_4layer);
                
                el81 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt8_1layer);
                
                el82 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt8_2layer);
                el83 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt8_3layer);
                el84 = pattern(txarray,fc,0,ElRange,...
                    'PropagationSpeed',c,...
                    'CoordinateSystem','polar',...
                    'Type','powerdB',...
                    'Weights',wt8_4layer);
                
                subplot(4,4,2);
                plot(ElRange,el11,"b",ElRange,el12,"r",ElRange,el13,"g",ElRange,el14,"y");
                axis ([-100 100 -50 0]);
                grid on;
                
                subplot(4,4,4);
                plot(ElRange,el21,"b",ElRange,el22,"r",ElRange,el23,"g",ElRange,el24,"y");
                axis ([-100 100 -50 0]);
                grid on;
                
                subplot(4,4,6);
                plot(ElRange,el31,"b",ElRange,el32,"r",ElRange,el33,"g",ElRange,el34,"y");
                axis ([-100 100 -50 0]);
                grid on;
                
                subplot(4,4,8);
                plot(ElRange,el41,"b",ElRange,el42,"r",ElRange,el43,"g",ElRange,el44,"y");
                axis ([-100 100 -50 0]);
                grid on;
                
                subplot(4,4,10);
                plot(ElRange,el51,"b",ElRange,el52,"r",ElRange,el53,"g",ElRange,el54,"y");
                axis ([-100 100 -50 0]);
                grid on;
                
                subplot(4,4,12);
                plot(ElRange,el61,"b",ElRange,el62,"r",ElRange,el63,"g",ElRange,el64,"y");
                axis ([-100 100 -50 0]);
                grid on;
                
                subplot(4,4,14);
                plot(ElRange,el71,"b",ElRange,el72,"r",ElRange,el73,"g",ElRange,el74,"y");
                axis ([-100 100 -50 0]);
                grid on;
                
                subplot(4,4,16);
                plot(ElRange,el81,"b",ElRange,el82,"r",ElRange,el83,"g",ElRange,el84,"y");
                axis ([-100 100 -50 0]);
                grid on;           
%                 % Plot 3D graph
%                 hFig = figure(3);
%                 
%                 subplot(2,2,[1 3]); 
%                 pattern(txarray,fc,[-180:180],[-90:90],...
%                     'PropagationSpeed',c,...
%                     'CoordinateSystem','polar',...
%                     'Type','powerdB',...
%                     'Weights',wt1_1layer);
%                 tStr = sprintf('i_{11} = %d, i_{12} = %d, i_2 = %d',i11,i12,i2);
%                 title(tStr);

                pause(0.05);

            
